from PyQt5 import QtCore, QtGui, QtWidgets, QtSvg

class ArticleCard(QtWidgets.QWidget):
    def __init__(self, image_path, index, parent=None):
        super().__init__(parent)
        self.setFixedHeight(300)
        self.setFixedWidth(370)
        self.article_image = QtWidgets.QLabel()
        self.article_image.setPixmap(QtGui.QPixmap(image_path))
        self.article_image.setObjectName("article_image_" + str(index))
        self.article_image.setMargin(0)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title = QtWidgets.QPushButton()
        self.article_title.setFont(font)
        self.article_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.article_title.setText("Elji Entah Apa")
        self.article_title.setObjectName("article_title_" + str(index))
        self.article_title.setStyleSheet("#article_title_" + str(index) + "{text-align:left; background-color: transparent;padding-left: 20px;color: #29B067;}")
       
        font.setPointSize(8)
        font.setBold(False)
        self.article_desc = QtWidgets.QLabel()
        self.article_desc.setText("ELJI has released a new smart fridge and it’s..")
        self.article_desc.setFont(font)
        self.article_desc.setContentsMargins(20, 0, 0, 0)

        article_title_container = QtWidgets.QWidget()
        article_title_container.setObjectName("article_title_container_"+str(index))
        article_title_container.setStyleSheet("#article_title_container_"+str(index)+"{background-color:white;border-bottom-left-radius: 8px;border-bottom-right-radius: 8px;border-top-left-radius: 0;border-top-right-radius: 0;}")
        article_title_container_layout = QtWidgets.QVBoxLayout()
        article_title_container_layout.addWidget(self.article_title)
        article_title_container_layout.addWidget(self.article_desc)
        article_title_container_layout.setSpacing(0)
        article_title_container.setLayout(article_title_container_layout)

        article_card_layout = QtWidgets.QVBoxLayout()
        article_card_layout.setContentsMargins(5, 0, 5, 0)
        article_card_layout.setSpacing(0)
        article_card_layout.addWidget(self.article_image)
        article_card_layout.addWidget(article_title_container)
        self.setLayout(article_card_layout)