from PyQt5 import QtCore, QtGui, QtWidgets, QtSvg

class RecipeCard(QtWidgets.QWidget):
    def __init__(self, image_path, index, parent=None):
        super().__init__(parent)
        self.setFixedHeight(280)
        self.setFixedWidth(370)
        self.recipe_image = QtWidgets.QLabel()
        self.recipe_image.setPixmap(QtGui.QPixmap(image_path))
        self.recipe_image.setObjectName("recipe_image_" + str(index))
        self.recipe_image.setMargin(0)
        self.recipe_title = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title.setFont(font)
        self.recipe_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recipe_title.setText("Crispy Pork Belly")
        self.recipe_title.setObjectName("recipe_title_" + str(index))
        self.recipe_title.setStyleSheet("#recipe_title_" + str(index) + "{text-align: left;background-color: white;padding: 20px;color: #F15D36;border-bottom-left-radius: 8px;border-bottom-right-radius: 8px;border-top-left-radius: 0;border-top-right-radius: 0;}")
        recipe_card_layout = QtWidgets.QVBoxLayout()
        recipe_card_layout.setContentsMargins(5, 0, 5, 0)
        recipe_card_layout.setSpacing(0)
        recipe_card_layout.addWidget(self.recipe_image)
        recipe_card_layout.addWidget(self.recipe_title)
        self.setLayout(recipe_card_layout)