# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Change path directory to root
import sys
import os
root_dir = os.path.abspath(os.path.join(os.getcwd()))
sys.path.append(root_dir)

from PyQt5 import QtCore, QtGui, QtWidgets
from src.ui.sidebar.sidebar import *
import ui_home_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1621, 1142)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = Sidebar(self.centralwidget)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 71, 1081))
        self.sidebar.setStyleSheet("#sidebar {\n"
"    background: #FFFFFF;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.25);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        temp_sidebar = Sidebar()
        self.verticalLayout.addWidget(temp_sidebar)
#         self.verticalLayout.setSpacing(20)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.logo = QtWidgets.QLabel(self.sidebar)
#         self.logo.setAlignment(QtCore.Qt.AlignCenter)
#         self.logo.setObjectName("logo")
#         self.verticalLayout.addWidget(self.logo)
#         self.home_button = QtWidgets.QPushButton(self.sidebar)
#         self.home_button.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.home_button.setStyleSheet("#home_button{\n"
# "    background: transparent;\n"
# "}")
#         self.home_button.setText("")
#         icon = QtGui.QIcon()
#         icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.home_button.setIcon(icon)
#         self.home_button.setIconSize(QtCore.QSize(32, 32))
#         self.home_button.setObjectName("home_button")
#         self.verticalLayout.addWidget(self.home_button)
#         self.recipe_button = QtWidgets.QPushButton(self.sidebar)
#         self.recipe_button.setStyleSheet("#recipe_button{\n"
# "    background: transparent;\n"
# "}")
#         self.recipe_button.setText("")
#         icon1 = QtGui.QIcon()
#         icon1.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_recipe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.recipe_button.setIcon(icon1)
#         self.recipe_button.setIconSize(QtCore.QSize(32, 32))
#         self.recipe_button.setObjectName("recipe_button")
#         self.verticalLayout.addWidget(self.recipe_button)
#         self.article_button = QtWidgets.QPushButton(self.sidebar)
#         self.article_button.setStyleSheet("#article_button{\n"
# "    background: transparent;\n"
# "}")
#         self.article_button.setText("")
#         icon2 = QtGui.QIcon()
#         icon2.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_article.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.article_button.setIcon(icon2)
#         self.article_button.setIconSize(QtCore.QSize(32, 32))
#         self.article_button.setObjectName("article_button")
#         self.verticalLayout.addWidget(self.article_button)
#         spacerItem = QtWidgets.QSpacerItem(20, 330, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         self.verticalLayout.addItem(spacerItem)
        self.home_title_container = QtWidgets.QWidget(self.centralwidget)
        self.home_title_container.setGeometry(QtCore.QRect(110, 60, 621, 91))
        self.home_title_container.setObjectName("home_title_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.home_title_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_title = QtWidgets.QLabel(self.home_title_container)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.home_title.setFont(font)
        self.home_title.setStyleSheet("#home_title{\n"
"    color: rgb(255, 207, 82);\n"
"}\n"
"")
        self.home_title.setTextFormat(QtCore.Qt.AutoText)
        self.home_title.setObjectName("home_title")
        self.verticalLayout_2.addWidget(self.home_title)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 231, 1278, 375))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(80)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.recipe_card_2 = QtWidgets.QVBoxLayout()
        self.recipe_card_2.setContentsMargins(5, -1, 5, -1)
        self.recipe_card_2.setSpacing(0)
        self.recipe_card_2.setObjectName("recipe_card_2")
        self.recipe_image_2 = QtWidgets.QLabel(self.widget)
        self.recipe_image_2.setText("")
        self.recipe_image_2.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.recipe_image_2.setObjectName("recipe_image_2")
        self.recipe_card_2.addWidget(self.recipe_image_2)
        self.recipe_title_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title_2.setFont(font)
        self.recipe_title_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recipe_title_2.setStyleSheet("#recipe_title_2 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.recipe_title_2.setAutoRepeatDelay(0)
        self.recipe_title_2.setAutoRepeatInterval(0)
        self.recipe_title_2.setObjectName("recipe_title_2")
        self.recipe_card_2.addWidget(self.recipe_title_2)
        self.gridLayout_3.addLayout(self.recipe_card_2, 0, 1, 1, 1)
        self.recipe_card_3 = QtWidgets.QVBoxLayout()
        self.recipe_card_3.setContentsMargins(5, -1, 5, -1)
        self.recipe_card_3.setSpacing(0)
        self.recipe_card_3.setObjectName("recipe_card_3")
        self.recipe_image_3 = QtWidgets.QLabel(self.widget)
        self.recipe_image_3.setText("")
        self.recipe_image_3.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.recipe_image_3.setObjectName("recipe_image_3")
        self.recipe_card_3.addWidget(self.recipe_image_3)
        self.recipe_title_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title_3.setFont(font)
        self.recipe_title_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recipe_title_3.setStyleSheet("#recipe_title_3 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.recipe_title_3.setAutoRepeatDelay(0)
        self.recipe_title_3.setAutoRepeatInterval(0)
        self.recipe_title_3.setObjectName("recipe_title_3")
        self.recipe_card_3.addWidget(self.recipe_title_3)
        self.gridLayout_3.addLayout(self.recipe_card_3, 0, 2, 1, 1)
        self.recipe_card = QtWidgets.QVBoxLayout()
        self.recipe_card.setContentsMargins(5, -1, 5, -1)
        self.recipe_card.setSpacing(0)
        self.recipe_card.setObjectName("recipe_card")
        self.recipe_image = QtWidgets.QLabel(self.widget)
        self.recipe_image.setText("")
        self.recipe_image.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.recipe_image.setObjectName("recipe_image")
        self.recipe_card.addWidget(self.recipe_image)
        self.recipe_title = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title.setFont(font)
        self.recipe_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recipe_title.setStyleSheet("#recipe_title {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.recipe_title.setAutoRepeatDelay(0)
        self.recipe_title.setAutoRepeatInterval(0)
        self.recipe_title.setObjectName("recipe_title")
        self.recipe_card.addWidget(self.recipe_title)
        self.gridLayout_3.addLayout(self.recipe_card, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 4)
        self.see_all_recipe_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.see_all_recipe_button.setFont(font)
        self.see_all_recipe_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.see_all_recipe_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.see_all_recipe_button.setAutoFillBackground(False)
        self.see_all_recipe_button.setStyleSheet("#see_all_recipe_button{\n"
"    color :rgb(241, 93, 54);\n"
"    background-color: transparent;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_chevron_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.see_all_recipe_button.setIcon(icon3)
        self.see_all_recipe_button.setObjectName("see_all_recipe_button")
        self.gridLayout_2.addWidget(self.see_all_recipe_button, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.recipe_heading_container = QtWidgets.QWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        self.recipe_heading_container.setFont(font)
        self.recipe_heading_container.setObjectName("recipe_heading_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.recipe_heading_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.recipe_heading = QtWidgets.QLabel(self.recipe_heading_container)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_heading.setFont(font)
        self.recipe_heading.setStyleSheet("#recipe_heading{\n"
"    color: rgb(241, 93, 54);\n"
"}\n"
"")
        self.recipe_heading.setTextFormat(QtCore.Qt.AutoText)
        self.recipe_heading.setObjectName("recipe_heading")
        self.verticalLayout_3.addWidget(self.recipe_heading)
        self.gridLayout_2.addWidget(self.recipe_heading_container, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(150, 620, 1274, 381))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.see_all_article_button = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.see_all_article_button.setFont(font)
        self.see_all_article_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.see_all_article_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.see_all_article_button.setAutoFillBackground(False)
        self.see_all_article_button.setStyleSheet("#see_all_article_button{\n"
"    color :rgb(41, 176, 103);\n"
"    background-color: transparent;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_chevron_right_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.see_all_article_button.setIcon(icon4)
        self.see_all_article_button.setObjectName("see_all_article_button")
        self.gridLayout.addWidget(self.see_all_article_button, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(80)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.article_image = QtWidgets.QLabel(self.widget1)
        self.article_image.setText("")
        self.article_image.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.article_image.setObjectName("article_image")
        self.verticalLayout_5.addWidget(self.article_image)
        self.article_title_container = QtWidgets.QWidget(self.widget1)
        self.article_title_container.setStyleSheet("#article_title_container{\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.article_title_container.setObjectName("article_title_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.article_title_container)
        self.verticalLayout_4.setContentsMargins(12, 9, -1, -1)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.article_title = QtWidgets.QPushButton(self.article_title_container)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title.setFont(font)
        self.article_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.article_title.setStyleSheet("#article_title {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    padding-left: 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(41, 176, 103);\n"
"}")
        self.article_title.setAutoRepeatDelay(0)
        self.article_title.setAutoRepeatInterval(0)
        self.article_title.setObjectName("article_title")
        self.verticalLayout_4.addWidget(self.article_title)
        self.description_container = QtWidgets.QWidget(self.article_title_container)
        self.description_container.setStyleSheet("#description_container{\n"
"    margin: 20px;\n"
"}")
        self.description_container.setObjectName("description_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.description_container)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.article_decription = QtWidgets.QLabel(self.description_container)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.article_decription.setFont(font)
        self.article_decription.setStyleSheet("")
        self.article_decription.setObjectName("article_decription")
        self.horizontalLayout.addWidget(self.article_decription)
        self.verticalLayout_4.addWidget(self.description_container)
        self.verticalLayout_5.addWidget(self.article_title_container)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.article_card_2 = QtWidgets.QVBoxLayout()
        self.article_card_2.setContentsMargins(5, -1, 5, -1)
        self.article_card_2.setSpacing(0)
        self.article_card_2.setObjectName("article_card_2")
        self.article_image_2 = QtWidgets.QLabel(self.widget1)
        self.article_image_2.setText("")
        self.article_image_2.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.article_image_2.setObjectName("article_image_2")
        self.article_card_2.addWidget(self.article_image_2)
        self.article_title_container_2 = QtWidgets.QWidget(self.widget1)
        self.article_title_container_2.setStyleSheet("#article_title_container_2{\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.article_title_container_2.setObjectName("article_title_container_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.article_title_container_2)
        self.verticalLayout_7.setContentsMargins(12, 9, -1, -1)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.article_title_2 = QtWidgets.QPushButton(self.article_title_container_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title_2.setFont(font)
        self.article_title_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.article_title_2.setStyleSheet("#article_title_2 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    padding-left: 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(41, 176, 103);\n"
"}")
        self.article_title_2.setAutoRepeatDelay(0)
        self.article_title_2.setAutoRepeatInterval(0)
        self.article_title_2.setObjectName("article_title_2")
        self.verticalLayout_7.addWidget(self.article_title_2)
        self.description_container_2 = QtWidgets.QWidget(self.article_title_container_2)
        self.description_container_2.setStyleSheet("#description_container_2{\n"
"    margin: 20px;\n"
"}")
        self.description_container_2.setObjectName("description_container_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.description_container_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.article_decription_2 = QtWidgets.QLabel(self.description_container_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.article_decription_2.setFont(font)
        self.article_decription_2.setStyleSheet("")
        self.article_decription_2.setObjectName("article_decription_2")
        self.horizontalLayout_2.addWidget(self.article_decription_2)
        self.verticalLayout_7.addWidget(self.description_container_2)
        self.article_card_2.addWidget(self.article_title_container_2)
        self.horizontalLayout_4.addLayout(self.article_card_2)
        self.article_card_3 = QtWidgets.QVBoxLayout()
        self.article_card_3.setContentsMargins(5, -1, 5, -1)
        self.article_card_3.setSpacing(0)
        self.article_card_3.setObjectName("article_card_3")
        self.article_image_3 = QtWidgets.QLabel(self.widget1)
        self.article_image_3.setText("")
        self.article_image_3.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.article_image_3.setObjectName("article_image_3")
        self.article_card_3.addWidget(self.article_image_3)
        self.article_title_container_3 = QtWidgets.QWidget(self.widget1)
        self.article_title_container_3.setStyleSheet("#article_title_container_3{\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.article_title_container_3.setObjectName("article_title_container_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.article_title_container_3)
        self.verticalLayout_8.setContentsMargins(12, 9, -1, -1)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.article_title_3 = QtWidgets.QPushButton(self.article_title_container_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title_3.setFont(font)
        self.article_title_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.article_title_3.setStyleSheet("#article_title_3 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    padding-left: 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(41, 176, 103);\n"
"}")
        self.article_title_3.setAutoRepeatDelay(0)
        self.article_title_3.setAutoRepeatInterval(0)
        self.article_title_3.setObjectName("article_title_3")
        self.verticalLayout_8.addWidget(self.article_title_3)
        self.description_container_3 = QtWidgets.QWidget(self.article_title_container_3)
        self.description_container_3.setStyleSheet("#description_container_3{\n"
"    margin: 20px;\n"
"}")
        self.description_container_3.setObjectName("description_container_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.description_container_3)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.article_decription_3 = QtWidgets.QLabel(self.description_container_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.article_decription_3.setFont(font)
        self.article_decription_3.setStyleSheet("")
        self.article_decription_3.setObjectName("article_decription_3")
        self.horizontalLayout_3.addWidget(self.article_decription_3)
        self.verticalLayout_8.addWidget(self.description_container_3)
        self.article_card_3.addWidget(self.article_title_container_3)
        self.horizontalLayout_4.addLayout(self.article_card_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 3)
        self.article_heading = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.article_heading.setFont(font)
        self.article_heading.setStyleSheet("#article_heading{\n"
"    color: rgb(41, 176, 103);\n"
"}\n"
"")
        self.article_heading.setTextFormat(QtCore.Qt.AutoText)
        self.article_heading.setObjectName("article_heading")
        self.gridLayout.addWidget(self.article_heading, 0, 0, 1, 1)
        self.sidebar.raise_()
        self.home_title_container.raise_()
        self.recipe_heading_container.raise_()
        self.recipe_heading_container.raise_()
        self.see_all_recipe_button.raise_()
        self.see_all_article_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.logo.setText(_translate("MainWindow", "Logo"))
        self.home_title.setText(_translate("MainWindow", "Welcome to Cookpaw"))
        self.recipe_title_2.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.recipe_title_3.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.recipe_title.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.see_all_recipe_button.setText(_translate("MainWindow", "See All Recipes"))
        self.recipe_heading.setText(_translate("MainWindow", "Check out our latest recipe collection!"))
        self.see_all_article_button.setText(_translate("MainWindow", "See All Articles"))
        self.article_title.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.article_decription.setText(_translate("MainWindow", "ELJI has released a new smart fridge and it’s.."))
        self.article_title_2.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.article_decription_2.setText(_translate("MainWindow", "ELJI has released a new smart fridge and it’s.."))
        self.article_title_3.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.article_decription_3.setText(_translate("MainWindow", "ELJI has released a new smart fridge and it’s.."))
        self.article_heading.setText(_translate("MainWindow", "Check out our latest article collection!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
