# Form implementation generated from reading ui file 'd:\lessons\SEM 4\REKAYASA PERANGKAT LUNAK\TUBES\if2250-2023-k02-08-cookpaw\src\ui\pages\home\ui_home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 71, 901))
        self.sidebar.setStyleSheet("#sidebar {\n"
"    background: #FFFFFF;\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.25);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(parent=self.sidebar)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.home_button = QtWidgets.QPushButton(parent=self.sidebar)
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.home_button.setStyleSheet("#home_button{\n"
"    background: transparent;\n"
"}\n"
"")
        self.home_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(32, 32))
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.recipe_button = QtWidgets.QPushButton(parent=self.sidebar)
        self.recipe_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.recipe_button.setStyleSheet("#recipe_button{\n"
"    background: transparent;\n"
"}")
        self.recipe_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_recipe.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.recipe_button.setIcon(icon1)
        self.recipe_button.setIconSize(QtCore.QSize(32, 32))
        self.recipe_button.setObjectName("recipe_button")
        self.verticalLayout.addWidget(self.recipe_button)
        self.article_button = QtWidgets.QPushButton(parent=self.sidebar)
        self.article_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.article_button.setStyleSheet("#article_button{\n"
"    background: transparent;\n"
"}")
        self.article_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_article.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.article_button.setIcon(icon2)
        self.article_button.setIconSize(QtCore.QSize(32, 32))
        self.article_button.setObjectName("article_button")
        self.verticalLayout.addWidget(self.article_button)
        spacerItem = QtWidgets.QSpacerItem(20, 330, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 20, 1295, 838))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(20, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.home_title = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.home_title.setFont(font)
        self.home_title.setStyleSheet("#home_title{\n"
"    color: rgb(255, 207, 82);\n"
"}\n"
"")
        self.home_title.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.home_title.setObjectName("home_title")
        self.gridLayout.addWidget(self.home_title, 0, 0, 1, 1)
        self.recipe_section = QtWidgets.QGridLayout()
        self.recipe_section.setObjectName("recipe_section")
        self.recipe_carousel = QtWidgets.QGridLayout()
        self.recipe_carousel.setHorizontalSpacing(80)
        self.recipe_carousel.setObjectName("recipe_carousel")
        self.recipe_card_2 = QtWidgets.QVBoxLayout()
        self.recipe_card_2.setContentsMargins(5, -1, 5, -1)
        self.recipe_card_2.setSpacing(0)
        self.recipe_card_2.setObjectName("recipe_card_2")
        self.recipe_image_2 = QtWidgets.QLabel(parent=self.widget)
        self.recipe_image_2.setText("")
        self.recipe_image_2.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.recipe_image_2.setObjectName("recipe_image_2")
        self.recipe_card_2.addWidget(self.recipe_image_2)
        self.recipe_title_2 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title_2.setFont(font)
        self.recipe_title_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.recipe_title_2.setStyleSheet("#recipe_title_2 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.recipe_title_2.setAutoRepeatDelay(0)
        self.recipe_title_2.setAutoRepeatInterval(0)
        self.recipe_title_2.setObjectName("recipe_title_2")
        self.recipe_card_2.addWidget(self.recipe_title_2)
        self.recipe_carousel.addLayout(self.recipe_card_2, 0, 1, 1, 1)
        self.recipe_card_3 = QtWidgets.QVBoxLayout()
        self.recipe_card_3.setContentsMargins(5, -1, 5, -1)
        self.recipe_card_3.setSpacing(0)
        self.recipe_card_3.setObjectName("recipe_card_3")
        self.recipe_image_3 = QtWidgets.QLabel(parent=self.widget)
        self.recipe_image_3.setText("")
        self.recipe_image_3.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.recipe_image_3.setObjectName("recipe_image_3")
        self.recipe_card_3.addWidget(self.recipe_image_3)
        self.recipe_title_3 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title_3.setFont(font)
        self.recipe_title_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.recipe_title_3.setStyleSheet("#recipe_title_3 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.recipe_title_3.setAutoRepeatDelay(0)
        self.recipe_title_3.setAutoRepeatInterval(0)
        self.recipe_title_3.setObjectName("recipe_title_3")
        self.recipe_card_3.addWidget(self.recipe_title_3)
        self.recipe_carousel.addLayout(self.recipe_card_3, 0, 2, 1, 1)
        self.recipe_card = QtWidgets.QVBoxLayout()
        self.recipe_card.setContentsMargins(5, -1, 5, -1)
        self.recipe_card.setSpacing(0)
        self.recipe_card.setObjectName("recipe_card")
        self.recipe_image = QtWidgets.QLabel(parent=self.widget)
        self.recipe_image.setText("")
        self.recipe_image.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.recipe_image.setObjectName("recipe_image")
        self.recipe_card.addWidget(self.recipe_image)
        self.recipe_title = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_title.setFont(font)
        self.recipe_title.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.recipe_title.setStyleSheet("#recipe_title {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.recipe_title.setAutoRepeatDelay(0)
        self.recipe_title.setAutoRepeatInterval(0)
        self.recipe_title.setObjectName("recipe_title")
        self.recipe_card.addWidget(self.recipe_title)
        self.recipe_carousel.addLayout(self.recipe_card, 0, 0, 1, 1)
        self.recipe_section.addLayout(self.recipe_carousel, 1, 0, 1, 3)
        self.see_all_recipe_button = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.see_all_recipe_button.setFont(font)
        self.see_all_recipe_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.see_all_recipe_button.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.see_all_recipe_button.setAutoFillBackground(False)
        self.see_all_recipe_button.setStyleSheet("#see_all_recipe_button{\n"
"    color :rgb(241, 93, 54);\n"
"    background-color: transparent;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_chevron_right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.see_all_recipe_button.setIcon(icon3)
        self.see_all_recipe_button.setObjectName("see_all_recipe_button")
        self.recipe_section.addWidget(self.see_all_recipe_button, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.recipe_section.addItem(spacerItem1, 0, 1, 1, 1)
        self.recipe_heading = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.recipe_heading.setFont(font)
        self.recipe_heading.setStyleSheet("#recipe_heading{\n"
"    color: rgb(241, 93, 54);\n"
"}\n"
"")
        self.recipe_heading.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.recipe_heading.setObjectName("recipe_heading")
        self.recipe_section.addWidget(self.recipe_heading, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.recipe_section, 1, 0, 1, 1)
        self.article_section = QtWidgets.QGridLayout()
        self.article_section.setObjectName("article_section")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.article_section.addItem(spacerItem2, 0, 1, 1, 1)
        self.see_all_article_button = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.see_all_article_button.setFont(font)
        self.see_all_article_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.see_all_article_button.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.see_all_article_button.setAutoFillBackground(False)
        self.see_all_article_button.setStyleSheet("#see_all_article_button{\n"
"    color :rgb(41, 176, 103);\n"
"    background-color: transparent;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/assets/icons/icon_chevron_right_green.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.see_all_article_button.setIcon(icon4)
        self.see_all_article_button.setObjectName("see_all_article_button")
        self.article_section.addWidget(self.see_all_article_button, 0, 2, 1, 1)
        self.article_carousel = QtWidgets.QHBoxLayout()
        self.article_carousel.setSpacing(80)
        self.article_carousel.setObjectName("article_carousel")
        self.article_card = QtWidgets.QVBoxLayout()
        self.article_card.setContentsMargins(5, -1, 5, -1)
        self.article_card.setSpacing(0)
        self.article_card.setObjectName("article_card")
        self.article_image = QtWidgets.QLabel(parent=self.widget)
        self.article_image.setText("")
        self.article_image.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.article_image.setObjectName("article_image")
        self.article_card.addWidget(self.article_image)
        self.article_title_container = QtWidgets.QWidget(parent=self.widget)
        self.article_title_container.setStyleSheet("#article_title_container{\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.article_title_container.setObjectName("article_title_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.article_title_container)
        self.verticalLayout_4.setContentsMargins(12, 9, -1, -1)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.article_title = QtWidgets.QPushButton(parent=self.article_title_container)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title.setFont(font)
        self.article_title.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.article_title.setStyleSheet("#article_title {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    padding-left: 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(41, 176, 103);\n"
"}")
        self.article_title.setAutoRepeatDelay(0)
        self.article_title.setAutoRepeatInterval(0)
        self.article_title.setObjectName("article_title")
        self.verticalLayout_4.addWidget(self.article_title)
        self.description_container = QtWidgets.QWidget(parent=self.article_title_container)
        self.description_container.setStyleSheet("#description_container{\n"
"    margin: 20px;\n"
"}")
        self.description_container.setObjectName("description_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.description_container)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.article_decription = QtWidgets.QLabel(parent=self.description_container)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.article_decription.setFont(font)
        self.article_decription.setStyleSheet("")
        self.article_decription.setObjectName("article_decription")
        self.horizontalLayout.addWidget(self.article_decription)
        self.verticalLayout_4.addWidget(self.description_container)
        self.article_card.addWidget(self.article_title_container)
        self.article_carousel.addLayout(self.article_card)
        self.article_card_2 = QtWidgets.QVBoxLayout()
        self.article_card_2.setContentsMargins(5, -1, 5, -1)
        self.article_card_2.setSpacing(0)
        self.article_card_2.setObjectName("article_card_2")
        self.article_image_2 = QtWidgets.QLabel(parent=self.widget)
        self.article_image_2.setText("")
        self.article_image_2.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.article_image_2.setObjectName("article_image_2")
        self.article_card_2.addWidget(self.article_image_2)
        self.article_title_container_2 = QtWidgets.QWidget(parent=self.widget)
        self.article_title_container_2.setStyleSheet("#article_title_container_2{\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.article_title_container_2.setObjectName("article_title_container_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.article_title_container_2)
        self.verticalLayout_7.setContentsMargins(12, 9, -1, -1)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.article_title_2 = QtWidgets.QPushButton(parent=self.article_title_container_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title_2.setFont(font)
        self.article_title_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.article_title_2.setStyleSheet("#article_title_2 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    padding-left: 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(41, 176, 103);\n"
"}")
        self.article_title_2.setAutoRepeatDelay(0)
        self.article_title_2.setAutoRepeatInterval(0)
        self.article_title_2.setObjectName("article_title_2")
        self.verticalLayout_7.addWidget(self.article_title_2)
        self.description_container_2 = QtWidgets.QWidget(parent=self.article_title_container_2)
        self.description_container_2.setStyleSheet("#description_container_2{\n"
"    margin: 20px;\n"
"}")
        self.description_container_2.setObjectName("description_container_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.description_container_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.article_decription_2 = QtWidgets.QLabel(parent=self.description_container_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.article_decription_2.setFont(font)
        self.article_decription_2.setStyleSheet("")
        self.article_decription_2.setObjectName("article_decription_2")
        self.horizontalLayout_2.addWidget(self.article_decription_2)
        self.verticalLayout_7.addWidget(self.description_container_2)
        self.article_card_2.addWidget(self.article_title_container_2)
        self.article_carousel.addLayout(self.article_card_2)
        self.article_card_3 = QtWidgets.QVBoxLayout()
        self.article_card_3.setContentsMargins(5, -1, 5, -1)
        self.article_card_3.setSpacing(0)
        self.article_card_3.setObjectName("article_card_3")
        self.article_image_3 = QtWidgets.QLabel(parent=self.widget)
        self.article_image_3.setText("")
        self.article_image_3.setPixmap(QtGui.QPixmap(":/images/assets/images/images_recipe/image_pork_belly.png"))
        self.article_image_3.setObjectName("article_image_3")
        self.article_card_3.addWidget(self.article_image_3)
        self.article_title_container_3 = QtWidgets.QWidget(parent=self.widget)
        self.article_title_container_3.setStyleSheet("#article_title_container_3{\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    background: white;\n"
"    padding: 20px;\n"
"    color: rgb(255, 207, 82);\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"}")
        self.article_title_container_3.setObjectName("article_title_container_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.article_title_container_3)
        self.verticalLayout_8.setContentsMargins(12, 9, -1, -1)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.article_title_3 = QtWidgets.QPushButton(parent=self.article_title_container_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.article_title_3.setFont(font)
        self.article_title_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.article_title_3.setStyleSheet("#article_title_3 {\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.25);\n"
"    text-align : left;\n"
"    padding-left: 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(41, 176, 103);\n"
"}")
        self.article_title_3.setAutoRepeatDelay(0)
        self.article_title_3.setAutoRepeatInterval(0)
        self.article_title_3.setObjectName("article_title_3")
        self.verticalLayout_8.addWidget(self.article_title_3)
        self.description_container_3 = QtWidgets.QWidget(parent=self.article_title_container_3)
        self.description_container_3.setStyleSheet("#description_container_3{\n"
"    margin: 20px;\n"
"}")
        self.description_container_3.setObjectName("description_container_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.description_container_3)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.article_decription_3 = QtWidgets.QLabel(parent=self.description_container_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.article_decription_3.setFont(font)
        self.article_decription_3.setStyleSheet("")
        self.article_decription_3.setObjectName("article_decription_3")
        self.horizontalLayout_3.addWidget(self.article_decription_3)
        self.verticalLayout_8.addWidget(self.description_container_3)
        self.article_card_3.addWidget(self.article_title_container_3)
        self.article_carousel.addLayout(self.article_card_3)
        self.article_section.addLayout(self.article_carousel, 1, 0, 1, 3)
        self.article_heading = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.article_heading.setFont(font)
        self.article_heading.setStyleSheet("#article_heading{\n"
"    color: rgb(41, 176, 103);\n"
"}\n"
"")
        self.article_heading.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.article_heading.setObjectName("article_heading")
        self.article_section.addWidget(self.article_heading, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.article_section, 2, 0, 1, 1)
        self.sidebar.raise_()
        self.see_all_recipe_button.raise_()
        self.see_all_article_button.raise_()
        self.home_title.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "Logo"))
        self.home_title.setText(_translate("MainWindow", "Welcome to Cookpaw"))
        self.recipe_title_2.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.recipe_title_3.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.recipe_title.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.see_all_recipe_button.setText(_translate("MainWindow", "See All Recipes"))
        self.recipe_heading.setText(_translate("MainWindow", "Check out our latest recipe collection!"))
        self.see_all_article_button.setText(_translate("MainWindow", "See All Articles"))
        self.article_title.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.article_decription.setText(_translate("MainWindow", "ELJI has released a new smart fridge and it’s.."))
        self.article_title_2.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.article_decription_2.setText(_translate("MainWindow", "ELJI has released a new smart fridge and it’s.."))
        self.article_title_3.setText(_translate("MainWindow", "Crispy Pork Belly"))
        self.article_decription_3.setText(_translate("MainWindow", "ELJI has released a new smart fridge and it’s.."))
        self.article_heading.setText(_translate("MainWindow", "Check out our latest article collection!"))
